---
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        selector: true
  server:
    service:
      type: "LoadBalancer"
    extraArgs:
    - --insecure
  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        selector: true
  dex:
    enabled: true
  redis:
    enabled: true